dist: xenial
sudo: required
services:
  - docker
language: go
go:
  - "1.14.x"

script:
- make test
- make vet

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on

